{{ if or (eq .chezmoi.os "darwin") (eq .chezmoi.os "linux") -}}
[".local/share/zsh-nvm"]
    type = "git-repo"
    url = "https://github.com/lukechilds/zsh-nvm.git"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/vim-tmux-navigator"]
    type = "git-repo"
    url = "https://github.com/christoomey/vim-tmux-navigator.git"
    refreshPeriod = "168h"
[".local/share/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
{{- end }}
[".config/yazi/flavors/tokyo-night.yazi"]
    type = "git-repo"
    url = "https://github.com/BennyOe/tokyo-night.yazi.git"
    refreshPeriod = "168h"
