{{ if eq .chezmoi.os "linux" -}}
{{ if eq .chezmoi.osRelease.id "ubuntu" -}}
[".local/bin/starship"]
    type = "file"
    url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/starship".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout"]
{{ end }}
[".local/bin/lf"]
    type = "file"
    url = "https://github.com/gokcehan/lf/releases/latest/download/lf-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/lf".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout"]

[".local/share/zsh-nvm"]
    type = "git-repo"
    url = "https://github.com/lukechilds/zsh-nvm.git"
    refreshPeriod = "168h"
{{- end }}
