# general
alias ..='cd ..'
alias ...='cd ../..'
alias btop='bpytop'
alias c='chezmoi'
alias cad='chezmoi add'
alias cap='chezmoi apply'
alias ccd='chezmoi cd'
alias cdi='chezmoi diff'
alias cls='clear'
alias cst='chezmoi status'
alias e='exit'
alias h='history'
alias l='ls -alh'
alias ll='ls -lh'
alias llt='ls -lhrt'
alias ls='ls --color=auto'
alias lt='ls -alhrt'
alias md='mkdir -p'
alias rd='rmdir'

# git
# from https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
alias g='git'
alias ga='git add'
alias gb='git branch'
alias gbD='git branch --delete --force'
alias gbg='git branch -vv | grep ": gone\]"'
alias gbgD='local res=$(gbg | awk '"'"'{print $1}'"'"') && [[ $res ]] && echo $res | xargs git branch --delete --force'
alias gcl='git clone --recurse-submodules'
alias gc='git commit --verbose'
alias gcmsg='git commit --verbose --message'
alias gc!='git commit --verbose --amend'
alias gd='git diff'
alias gdca='git diff --cached'
alias gmom='git merge origin/$(git_main_branch)'
alias gl='git pull'
alias glg='git log --stat'
alias gp='git push'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias grb='git rebase'
alias grbc='git rebase --continue'
alias grbom='git rebase origin/$(git_main_branch)'
alias gra='git remote add'
alias grv='git remote --verbose'
alias grrm='git remote remove'
alias grh='git reset'
alias grhh='git reset --hard'
alias grs='git restore'
alias grst='git restore --staged'
alias grm='git rm'
alias grmc='git rm --cached'
alias gsta='git stash push'
alias gstp='git stash pop'
alias gst='git status'
alias gsu='git submodule update'
alias gsw='git switch'
alias gswc='git switch --create'
alias gswm='git switch $(git_main_branch)'
alias gwt='git worktree'
alias gwtls='git worktree list'
alias gwtmv='git worktree move'
alias gwtrm='git worktree remove'
# from myself
alias grhs='git reset --soft'
