# general
alias ..='cd ..'
alias ...='cd ../..'
#alias btop='bpytop'
alias c='chezmoi'
alias cad='chezmoi add'
alias cap='chezmoi apply'
alias ccd='chezmoi cd'
alias cdi='chezmoi diff'
alias cls='clear'
alias cst='chezmoi status'
alias cup='chezmoi update'
alias e='exit'
alias h='history'
alias lg='lazygit'
alias ls='lsd'
alias l='ls -alh'
alias ll='ls -lh'
alias llt='ls -lhrt'
alias lt='ls -alhrt'
alias md='mkdir -p'
alias rd='rmdir'

# git
# from https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
alias g='git'
alias gbg='git branch -vv | grep ": gone\]"'
alias gbgD='local res=$(gbg | awk '"'"'{print $1}'"'"') && [[ $res ]] && echo $res | xargs git branch --delete --force'
alias gc!='git commit --verbose --amend'
alias gmom='git merge origin/$(git_main_branch)'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias grbom='git rebase origin/$(git_main_branch)'
alias gswm='git switch $(git_main_branch)'
